import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export default function ImprintPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0f] text-zinc-100">
      <div className="mx-auto max-w-3xl px-6 py-20 lg:py-32">
        <Link 
          href="/" 
          className="group mb-12 inline-flex items-center gap-2 text-sm text-zinc-500 transition-colors hover:text-white"
        >
          <ChevronLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
          Back to home
        </Link>

        <header className="mb-16">
          <h1 className="mb-4 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">Imprint</h1>
          <p className="text-zinc-500">Legal information about MeasyAI.</p>
        </header>

        <section className="glass space-y-10 rounded-3xl p-8 sm:p-12">
          <div className="space-y-4">
            <h2 className="text-xl font-bold text-white">Project Information</h2>
            <div className="grid gap-6 text-sm sm:grid-cols-2">
              <div className="space-y-1">
                <p className="text-zinc-500 uppercase tracking-wider text-[10px] font-bold">Provider</p>
                <p className="font-medium text-zinc-300">MeasyAI (by CraftingStudioPro)</p>
              </div>
              <div className="space-y-1">
                <p className="text-zinc-500 uppercase tracking-wider text-[10px] font-bold">Location</p>
                <p className="font-medium text-zinc-300">Germany</p>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-bold text-white">Contact Details</h2>
            <div className="grid gap-6 text-sm sm:grid-cols-2">
              <div className="space-y-1">
                <p className="text-zinc-500 uppercase tracking-wider text-[10px] font-bold">Support Email</p>
                <p className="font-medium text-zinc-300">support@measyai.com</p>
              </div>
              <div className="space-y-1">
                <p className="text-zinc-500 uppercase tracking-wider text-[10px] font-bold">Discord</p>
                <p className="font-medium text-zinc-300">discord.gg/measyai</p>
              </div>
            </div>
          </div>

          <div className="space-y-4 border-t border-white/5 pt-10">
            <p className="text-xs leading-relaxed text-zinc-500">
              Disclaimer: This application is currently in public beta. All intellectual property related to 
              Nova Core and MeasyAI is owned by CraftingStudioPro. We are not responsible for the 
              content generated by the AI models hosted on our platform.
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}
